#ifndef CORE_CORE_CONFIG_H
#define CORE_CORE_CONFIG_H

#define CORE_CLOCK_USE_HSE
#define CORE_CLOCK_HSE_FREQ 25000
#define CORE_CLOCK_SYSCLK_FREQ 102400

/*** CAN CONFIG PARAMETERS ***/
#define CAN_QUEUE_LENGTH 15

#define CAN1_PORT GPIOA
#define CAN2_PORT GPIOB
#define CAN3_PORT GPIOB
#define CAN1_PINS (GPIO_PIN_11 | GPIO_PIN_12)
#define CAN2_PINS (GPIO_PIN_12 | GPIO_PIN_13)
#define CAN3_PINS (GPIO_PIN_3 | GPIO_PIN_4)




#endif //CORE_CORE_CONFIG_H
